trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Validation
  displayName: Validation
  jobs:
  - job: Validation
    steps:
    - script: echo "Validating Enterprise DevSecOps Platform"
      displayName: Validation

- stage: Testing
  displayName: Testing
  dependsOn: Validation
  jobs:
  - job: Pytest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'

    - script: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest
        pytest app/test_app.py
      displayName: Run Pytest

- stage: Code_Quality
  displayName: Code Quality
  dependsOn: Testing
  jobs:
  - job: Pylint
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'

    - script: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pylint
        pylint app/app.py --disable=all --enable=E
      displayName: Run Pylint

- stage: Security_Scan
  displayName: Security Scan
  dependsOn: Code_Quality
  jobs:
  - job: Bandit
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'

    - script: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install bandit
        bandit -r app -x app/test_app.py
      displayName: Run Bandit

- stage: Kubernetes_Validation
  displayName: Kubernetes Validation
  dependsOn: Security_Scan
  jobs:
  - job: AKSValidation
    steps:
    - script: |
        echo "AKS Deployment Manifest Found"
        ls -la k8s
      displayName: Validate Kubernetes Manifests

- stage: Deploy_to_AKS
  displayName: Deploy to AKS
  dependsOn: Kubernetes_Validation
  jobs:
  - job: Deploy
    steps:
    - task: KubernetesManifest@1
      displayName: Deploy Deployment
      inputs:
        action: deploy
        kubernetesServiceConnection: aks-enterprise-devsecops-sc
        manifests: |
          k8s/deployment.yaml

    - task: KubernetesManifest@1
      displayName: Deploy Service
      inputs:
        action: deploy
        kubernetesServiceConnection: aks-enterprise-devsecops-sc
        manifests: |
          k8s/service.yaml
