trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Validation
  jobs:
  - job: Validation
    steps:
    - script: echo "Validating Enterprise DevSecOps Platform"
      displayName: "Validation"

- stage: Kubernetes_Validation
  dependsOn: Validation

  jobs:
  - job: AKSValidation

    steps:
    - script: |
        echo "AKS Deployment Manifest Found"
        ls -la k8s
      displayName: "Validate Kubernetes Manifests"
